// For more information, see https://crawlee.dev/
import { PlaywrightCrawler, RequestList, Configuration } from 'crawlee';
import { router } from './routes.js';
import randomstring from 'randomstring'
import { chromium } from 'playwright';

const config = Configuration.getGlobalConfig()
config.set('availableMemoryRatio', 0.95)
config.set('maxUsedCpuRatio', 0.95)
config.set('memoryMbytes', 22000)

const url = 'https://index.hu/'

const requestList = await RequestList.open('my-request-list', [
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
    { url, uniqueKey: randomstring.generate(5)},
]);

const crawler = new PlaywrightCrawler({
    // proxyConfiguration: new ProxyConfiguration({ proxyUrls: ['...'] }),
    requestHandler: router,
    requestList,
    useSessionPool: true,
    persistCookiesPerSession: true,
    minConcurrency: 1,
    maxConcurrency: 200,
    headless: true,
    requestHandlerTimeoutSecs: 107374,
    launchContext: {
        launcher: chromium,
        useIncognitoPages: true,
        // experimentalContainers: true,
        launchOptions: {
          args: [
            '--no-sandbox',
            '--disable-setuid-sandbox',
            '--disable-infobars',
            '--disable-dev-shm-usage',
            '--disable-accelerated-2d-canvas',
            '--no-first-run',
            '--no-service-autorun',
            '--password-store=basic',
            '--no-zygote',
            // '--single-process', // <- this one doesn't work in Windows
            '--disable-gpu'
          ]
        }
      },
});

await crawler.run();
